### ISSUE TITLE
You modified value twice in a single render

### ISSUE THREAD

**Issue by staskij** [shipshapecode/ember-flatpickr#115]
Simple twiddle to reproduce:
https://ember-twiddle.com/a14d945276da2982172c12caf1cb5364?openFiles=templates.application.hbs%2C

I can't understand what's causing the problem. Maybe didReceiveAttrs() which sets flatpickr date to value causes onChange to trigger again causing the mut helper to change the value again and thus updating value twice?

**Comment by rwwagner90** [comment]
@staskij sounds like it is related to the same thing as #114. Would you and @GCheung55 perhaps like to PR in a solution for this issue? 😄

**Comment by staskij** [comment]
Trying to solve this.
This is the same with some console log statements, showing that onChange is indeed called twice: 
https://ember-twiddle.com/a14d945276da2982172c12caf1cb5364/eb2b4a2584f97c485424316bafe3aefeebad4ec9?openFiles=components.ember-flatpickr.js%2C

Changing `flatpickr#setDate(value)` to `flatpickr#setDate(value, false)` in `didReceiveAttrs()` causes onChange not to be triggered, but I can't understand why the displayed format changes:
https://ember-twiddle.com/a14d945276da2982172c12caf1cb5364/3ca7273ef1697d15e3435678938221069578506c?openFiles=components.ember-flatpickr.js%2C

**Comment by jgadbois** [comment]
I'm also having this problem after upgrade

**Comment by evoactivity** [comment]
I'm currently developing an app with a lot of datepickers and the client is constantly checking my staging deploys, this problem didn't just break the datepickers, once you had interacted with one and received the error, _any_ other interaction with the app caused the error again, things isolated and unrelated to the datepicker would trigger the error.

I've gone and put in a hacky fix, in my component I now have this:

```
defaultDate: new Date(),

setDate: computed('date', {
  get() {
    return get(this, 'date');
  },
  set(key, value) {
    if (value !== null) {
      let [date] = value;
      set(this, 'date', date);
    }
  }
})
```

and my flatpickr component is setup like so

```
{{ ember-flatpickr
  onChange=(action (mut setDate))
  altInput=true
  value=(readonly setDate)
  altFormat="j F Y"
  mode="single"
  weekNumbers=true
  defaultDate=defaultDate
  altInputClass='form__control' }}
```

Whereas before I just had 

```
date: new Date()
```

```
{{ ember-flatpickr
  onChange=(action (mut date))
  altInput=true
  value=(readonly date)
  altFormat="j F Y"
  mode="single"
  weekNumbers=true
  altInputClass='form__control' }}
```

Instead of a computed property I tried having an action that set `date` but that would trigger the same issue, not sure why doing it as a computed property fixed it, if someone does know I'd be interested in learning why this works.

**Comment by GCheung55** [comment]
@evoactivity That's a good question. I'm not sure why this code is working for you. Because when the `setDate` `set` method is called, the `date` property is changed and since the `set` method isn't returning the value for caching, the `setDate` `get` method would be called from setting the `date` property.

Have you put in some logging in the set and get to see if it's going in a vicious cycle you don't see?

**Comment by evoactivity** [comment]
@GCheung55 I have, it logs just the once on set, but never runs get at all after set, which again, I have no idea why. I just hope flatpickr release the update soon so I can get rid of all this.

**Comment by rwwagner90** [comment]
@evoactivity in the meantime, you can downgrade flatpickr to `2.3.2`, which should fix this issue. Not sure when there will be a new release yet.

**Comment by irawel** [comment]
This problem still occurs with the latest ember-flatpickr with mode="range" option.
The ember-flatpickr component is initialiazed with following:
`mode= "range"`
`onChange=(action (mut dateValues))`
`value=(readonly dateValues)`
And when the date is set for the second time, `You modified value twice in a single render` error throws.
