### ISSUE TITLE
Not possible to use flatpickr with no theme

### ISSUE THREAD

**Issue by jgadbois** [shipshapecode/ember-flatpickr#90]
I'd like to use the default all white styles, but it seems like a theme is required (since it defaults to dark).   Is there a way to use no theme?

**Comment by rwwagner90** [comment]
@jgadbois I think you can set theme to `default`

**Comment by rwwagner90** [comment]
Just kidding. I will release a fix for this. Please stand by.

**Comment by jgadbois** [comment]
Thanks!  I actually tried that first, should have mentioned that.

**Comment by rwwagner90** [comment]
Released 1.1.4 which should fix this

**Comment by jgadbois** [comment]
Thanks!  It is still showing the dark theme for me with:

```
  var app = new EmberApp(defaults, {
      flatpickr: {
        theme: null·
      }
      // Add options here
    });
```

Could your default be overriding null?

**Comment by jgadbois** [comment]
Scratch that i didn't update via npm yet

**Comment by rwwagner90** [comment]
There is no default anymore. It just uses the vanilla flatpickr.css when there is no theme specified. You should be able to remove the config entirely.

**Comment by jgadbois** [comment]
Works great, thanks!
